name: M3u Fetch And Modify
on: 
  schedule: 
    - cron: 51 * * * *
  workflow_dispatch:
  repository_dispatch: #允许外部触发,cf worker定时任务延迟在1分钟以内
    types: [tvcron]
jobs:
  main:
    name: Fetch And Modify
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 允许推送代码
    env:
      ONLY_UPDATE_MIGU: false    # 在这里修改：true 表示只更新 migu_merged.m3u，false 表示更新所有文件
    
    steps: 
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Install Dependencies
      run: pip install requests

    # ---  Migu 处理---
    - name: Process Migu Files
      continue-on-error: true     # 即使失败也会继续执行后续块 
      run: |
        wget https://github.com/ioptu/migu_video/raw/refs/heads/main/migu.txt -O mig.m3u -t 2 --waitretry=5
        #python ./scripts/m3u_mergerng.py -i mig.m3u -o mg_m.m3u
        #python ./scripts/m3u_merger.py -i mg_m.m3u -o mg_merged.m3u
        ##python ./scripts/add_channel.py -i mg_merged.m3u -o mg_merged.m3u -a "搜狐剧场,https://hdl-vip-ws.qf.56.com/live/lc_11730.flv"
        python ./scripts/deduplicate.py -i mig.m3u -o mig_d.m3u
        python ./scripts/m3u_mergerng.py -i mig_d.m3u -o mig_d.m3u
        python ./scripts/m3u_merger.py -i mig_d.m3u -o mig_d.m3u
        ##python ./scripts/url_sorter.py -i mig_d.m3u -o mig_d.m3u -k "http" -ch "CCTV5+" -rn "CCTV5+"
        ##python ./scripts/add_channel.py -i mig_d.m3u -o mig_d.m3u -a "搜狐剧场,https://hdl-vip-ws.qf.56.com/live/lc_11730.flv"
        
    # --- pluto&rakuten 源处理  ---
    - name: Process pluto&rakuten Files
      if: env.ONLY_UPDATE_MIGU != 'true'    
      continue-on-error: true
      run: |
            #wget https://iptv-org.github.io/iptv/index.m3u -O io.m3u  -t 2 --waitretry=5
            #python ./scripts/extract.py --input io.m3u --output io.m3u --eoru 'pluto,pluto' -n
            #python ./scripts/m3u_merger.py -i io.m3u -o io_merged.m3u
            wget https://github.com/482349841209/rakuten-m3u-generator/raw/refs/heads/master/output/rakuten.m3u -O rkt.m3u  -t 2 --waitretry=5
            
    # --- httop 源处理  ---
    - name: Process httop Files
      if: env.ONLY_UPDATE_MIGU != 'false'    
      continue-on-error: true
      run: |
            #地址失效
            wget https://httop.top/hotel.m3u -O hp.m3u  -t 2 --waitretry=5
            python ./scripts/m3u_merger.py -i hp.m3u -o hp_merged.m3u
            python ./scripts/url_sortergr.py -i hp_merged.m3u -o hp_merged.m3u -gr '央视,卫视,其它' -gs
            
    # --- hotel 源处理 ---
    - name: Process hotel Files
      if: env.ONLY_UPDATE_MIGU != 'true'    
      continue-on-error: true
      run: |
            #与httop同样输出httop.m3u,最多同时启用一个
            wget http://120.27.21.75:20085/sub?biWVtPA3=txt -O htl.txt  -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i htl.txt -o htl.m3u
            python ./scripts/m3u_purifier.py -i htl.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i htl.m3u -o htl_merged.m3u
            python ./scripts/url_sortergr.py -i htl_merged.m3u -o htl_merged.m3u -gr '央视,卫视,其他' -gs  
            

    # --- hotel 源处理 2 ---
    - name: Process hotel Files 2
      if: env.ONLY_UPDATE_MIGU != 'true'    
      continue-on-error: true
      run: |
            wget https://github.com/zhlshrimp/Hotel_m3u/raw/refs/heads/main/lt.txt -O hlt.txt -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i hlt.txt -o hlt.m3u
            python ./scripts/extract.py --input hlt.m3u --output hlt.m3u --eoru '卫视高清,?' -n -r
            python ./scripts/m3u_purifier.py -i hlt.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i hlt.m3u -o hlt_merged.m3u
            python ./scripts/url_sortergr.py -i hlt_merged.m3u -o hlt_merged.m3u -gr '央视,卫视,其他' -gs  
            
            wget https://github.com/zhlshrimp/Hotel_m3u/raw/refs/heads/main/dx.txt -O hdx.txt -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i hdx.txt -o hdx.m3u
            python ./scripts/m3u_purifier.py -i hdx.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i hdx.m3u -o hdx_merged.m3u

            wget https://github.com/zhlshrimp/Hotel_m3u/raw/refs/heads/main/yd.txt -O hyd.txt -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i hyd.txt -o hyd.m3u
            python ./scripts/m3u_purifier.py -i hyd.m3u -n -mt 10
            python ./scripts/m3u_merger.py -i hyd.m3u -o hyd_merged.m3u
            
            
    # --- ---
    - name: Process iptv Files
      if: env.ONLY_UPDATE_MIGU != 'false'    
      continue-on-error: true
      run: |
            #无需频繁更新  # 与guovi源最多同时启用一个，都是处理源并输出iptv.m3u
            wget https://github.com/ioptu/migu_video/raw/refs/heads/main/iptv.txt -O ip.txt  -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i ip.txt -o ip.m3u
            python ./scripts/extract.py --input ip.m3u --output ip.m3u --eoru ',/dsdqca/' -n -r
            python ./scripts/m3u_merger.py -i ip.m3u -o ip_merged.m3u
            python ./scripts/url_sortergr.py -i ip_merged.m3u -o ip_merged.m3u -gr '央视,卫视,其他' -gs

    # --- guovin 源处理  ---
    - name: Process guovin Files
      if: env.ONLY_UPDATE_MIGU != 'false'    
      continue-on-error: true
      run: |
            wget https://raw.githubusercontent.com/Guovin/iptv-api/refs/heads/gd/output/result.m3u -O gop.m3u  -t 2 --waitretry=5
            python ./scripts/extract.py --input gop.m3u --output gop.m3u --eoru ',//38.75.136.137' -n
            python ./scripts/extract.py --input gop.m3u --output gop.m3u --eoru '更新时间,' -n -r
            python ./scripts/url_sorter.py -i gop.m3u -o gop.m3u -k "cctv5p" -ch "CCTV" -rn "CCTV5+" 
            python ./scripts/add_channel.py -i gop.m3u -o gop.m3u -r -a "五星体育,http://38.75.136.137:98/gslb/dsdqpub/wxtyhd.m3u8?auth=testpub;天津体育,http://38.75.136.137:98/gslb/dsdqpub/tjtv5.m3u8?auth=testpub"
            python ./scripts/m3u_merger.py -i gop.m3u -o gop_merged.m3u
            python ./scripts/deduplicate.py -i gop_merged.m3u -o gop_merged.m3u

    # ---  huuc 源处理  ---
    - name: Process luuc Files
      if: env.ONLY_UPDATE_MIGU != 'false'    
      continue-on-error: true
      run: |
            #无需频繁更新
            wget https://raw.githubusercontent.com/lwzlinyi/ziyong/refs/heads/main/live2.m3u -O live2.m3u  -t 2 --waitretry=5
            python ./scripts/extract.py --input live2.m3u --output t1op.m3u --eoru ',huuc' -n
            python ./scripts/deduplicate.py -i t1op.m3u -o t1output.m3u 
            
    # ---  lnott 源处理  ---
    - name: Process lnott Files
      if: env.ONLY_UPDATE_MIGU != 'false'
      continue-on-error: true
      run: |
            #无需频繁更新
            wget http://www.lyyytv.cn/yt/zhibo/1.txt -O 1.txt -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i 1.txt -o 1.m3u
            python ./scripts/extract.py --input 1.m3u --output t2op.m3u --eoru ',lnott' -n
            python ./scripts/deduplicate.py -i t2op.m3u -o t2output.m3u

    # ---  101.qzz.io 源处理  ---
    - name: Process 101.qzz.io Files
      if: env.ONLY_UPDATE_MIGU != 'false'
      continue-on-error: true
      run: |
            #无需频繁更新
            wget https://github.com/yishilaoxia/laoxia/raw/47a5dc7302327265fcf2610ae0951d1e41d6d0b4/output/gtdl0116.txt -O gtd.txt  -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i gtd.txt -o t4op.m3u
            python ./scripts/extract.py --input t4op.m3u --output tv4output.m3u --eoru ',cdn6.101.qzz.io' -n
            #python ./scripts/m3u_merger.py -i tv4output.m3u -o tv4output_merged.m3u
            
    # --- ---       
    - name: Process 港澳频道 Files
      if: env.ONLY_UPDATE_MIGU != 'false'
      continue-on-error: true
      run: |
            #无需频繁更新
            wget https://github.com/ioptu/migu_video/raw/ea459c3e6ce43d99aca23ef4524e649c7d71394d/%E6%B8%AF%E6%BE%B3%E9%A2%91%E9%81%93.txt -O hm.txt  -t 2 --waitretry=5
            node ./scripts/txt2m3u.js -i hm.txt -o tv5op.m3u
            python ./scripts/m3u_merger.py -i tv5op.m3u -o tv5op_merged.m3u
            
    # --- qqqtv 源处理  ---
    - name: Process Lite Files
      if: env.ONLY_UPDATE_MIGU != 'false'
      continue-on-error: true
      run: |
            #
            #wget https://github.com/xiaoran29/core/raw/refs/heads/main/output/lite.m3u -O lite.m3u  -t 2 --waitretry=5
            #python ./scripts/extract.py --input lite.m3u --output t3op.m3u --eoru ',qqqtv' -n
            #python ./scripts/m3u_merger.py -i t3op.m3u -o t3op_merged.m3u
            #python ./scripts/url_sorter.py -i t3op_merged.m3u -o t3op_ms.m3u -k 'HD&auth=666858,auth=66615415'

            #临时措施，目标直播源修正了频道名错误后应恢复使用以上注释代码块
            wget https://github.com/xiaoran29/core/raw/refs/heads/main/output/lite.m3u -O lite.m3u  -t 2 --waitretry=5
            python ./scripts/extract.py --input lite.m3u --output t3o.m3u --eoru ',qqqtv' -n
            python ./scripts/url_sorter.py -i t3o.m3u -o t3op.m3u -k "CCTV-5%2B" -ch "CCTV5" -rn "CCTV5+" 
            python ./scripts/m3u_merger.py -i t3op.m3u -o t3op_merged.m3u
            python ./scripts/url_sorter.py -i t3op_merged.m3u -o t3op_ms.m3u -k 'HD&auth=666858,auth=66615415'
            #目标直播源大量缺失qqqtv频道，恢复旧文件 暂停上游更新  #已备份到backup目录，保持跟随上游更新   
            #wget https://github.com/ioptu/IPTV.txt2m3u.player/raw/dcf291331d4e49d18d519e386d11c4278c76ccf2/yp.qqqtv.top.m3u -O qtv.m3u  -t 2 --waitretry=5
            #python ./scripts/url_sorter.py -i qtv.m3u -o qtvop.m3u -k "CCTV-5%2B" -ch "CCTV5" -rn "CCTV5+" 
            #python ./scripts/m3u_merger.py -i qtvop.m3u -o qtvop_merged.m3u
            #python ./scripts/url_sorter.py -i qtvop_merged.m3u -o qtvop_ms.m3u -k 'HD&auth=666858,auth=66615415'
        

    # --- Catvod 处理 ---
    - name: Process Catvod Files
      if: env.ONLY_UPDATE_MIGU != 'false'
      continue-on-error: true
      run: |
        wget https://github.com/xiaoran29/core/raw/refs/heads/main/output/lite.m3u -O lite.m3u -t 2 --waitretry=5
        python ./scripts/extract.py --input lite.m3u --output t3op2.m3u --eoru ',catvod.com' -n 
        python ./scripts/m3u_merger.py -i t3op2.m3u -o t3op2_merged.m3u
        python ./scripts/url_sorter.py -i t3op2_merged.m3u -o t3op2_ms.m3u -k 'CCTV-' -r
        
    # ---  汇总处理 ---
    - name: Final Merge 1
      if: env.ONLY_UPDATE_MIGU != 'false'
      continue-on-error: true
      run: |
        python ./scripts/m3u_merger.py -i t3op2_ms.m3u mg_m.m3u huuc_ipv6.m3u sh.lnott.top.m3u cdn6.101.qzz.io.m3u -o t0op_m.m3u
        python ./scripts/url_sorter.py -i t0op_m.m3u -o t0op_ms.m3u -k "catvod,luuc,miguvideo"
        python ./scripts/url_sorter.py -i t0op_ms.m3u -o t0op_ms.m3u -k "CCTV-" -r
        #python ./scripts/m3u_header_tool.py -i t0op_ms.m3u -c -E "https://gh-proxy.org/github.com/ioptu/migu_video/raw/refs/heads/main/e.xml"
        
    - name: Final Merge 2
      if: env.ONLY_UPDATE_MIGU != 'false'
      continue-on-error: true
      run: |       
        python ./scripts/url_sortergr.py -i t0op_m.m3u -o ttvop_m.m3u -gr "央视" -rg "央视" 
        python ./scripts/url_sortergr.py -i ttvop_m.m3u -o ttvop_m.m3u -gr "卫视" -rg "卫视" 
        python ./scripts/m3u_merger.py -i ttvop_m.m3u -o ttvop_m.m3u 
        python ./scripts/url_sorter.py -i ttvop_m.m3u -o ttvop_ms.m3u -k "catvod,luuc,miguvideo" 
        python ./scripts/url_sorter.py -i ttvop_ms.m3u -o ttvop_ms.m3u -k "CCTV-" -r 
        #python ./scripts/m3u_header_tool.py -i ttvop_ms.m3u -c -E "https://gh-proxy.org/github.com/ioptu/migu_video/raw/refs/heads/main/e.xml"

    # ---  提交推送 (这个步骤不建议加 continue-on-error，因为它是最终目标) ---
    - name: CommitAndPush
      run: |
        REPO_NAME="${GITHUB_REPOSITORY#*/}"
        git config --global user.email "github@github.com"
        git config --global user.name "Github Actions"
        
        git clone "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
        cd "$REPO_NAME" || exit 1 

        # 使用 [ -f ] 检查文件是否存在再移动，防止因前面某块失败导致文件缺失而报错退出
        [ -f ../mig_d.m3u ] && mv ../mig_d.m3u ./migu.m3u || echo "migu skip"
        [ -f ../mg_merged.m3u ] && mv ../mg_merged.m3u ./migu_merged.m3u || echo "migu_merged skip"
        
        if [ "$ONLY_UPDATE_MIGU" != "true" ]; then
          
          [ -f ../t1output.m3u ] && mv ../t1output.m3u ./huuc_ipv6.m3u || true
          [ -f ../t2output.m3u ] && mv ../t2output.m3u ./sh.lnott.top.m3u || true          
          [ -f ../tv4output.m3u ] && mv ../tv4output.m3u ./cdn6.101.qzz.io.m3u || true
          [ -f ../tv4output_merged.m3u ] && mv ../tv4output_merged.m3u ./cdn6.101.qzz.io_merged.m3u || true
          [ -f ../t3op.m3u ] && mv ../t3op.m3u ./yp.qqqtv.top.m3u || true
          [ -f ../t3op_ms.m3u ] && mv ../t3op_ms.m3u ./yp.qqqtv.top_merged.m3u || true
          [ -f ../t3op2.m3u ] && mv ../t3op2.m3u ./catvod.com.m3u || true
          [ -f ../t3op2_ms.m3u ] && mv ../t3op2_ms.m3u ./catvod.com_merged.m3u || true
          [ -f ../t0op_ms.m3u ] && mv ../t0op_ms.m3u ./tv_merged.m3u || true
          [ -f ../ttvop_ms.m3u ] && mv ../ttvop_ms.m3u ./ttv_merged.m3u || true
          [ -f ../tv5op.m3u ] && mv ../tv5op.m3u ./港澳.m3u || true
          [ -f ../tv5op_merged.m3u ] && mv ../tv5op_merged.m3u ./港澳_merged.m3u || true
          [ -f ../hp.m3u ] && mv ../hp.m3u ./httop.m3u || true
          [ -f ../hp_merged.m3u ] && mv ../hp_merged.m3u ./httop_merged.m3u || true 
          [ -f ../htl.m3u ] && mv ../htl.m3u ./httop.m3u || true
          [ -f ../htl_merged.m3u ] && mv ../htl_merged.m3u ./httop_merged.m3u || true 
          [ -f ../hlt_merged.m3u ] && mv ../hlt_merged.m3u ./htllt_merged.m3u || true   
          [ -f ../hdx_merged.m3u ] && mv ../hdx_merged.m3u ./htldx_merged.m3u || true  
          [ -f ../hyd_merged.m3u ] && mv ../hyd_merged.m3u ./htlyd_merged.m3u || true            
          [ -f ../gop.m3u ] && mv ../gop.m3u ./iptv.m3u || true
          [ -f ../gop_merged.m3u ] && mv ../gop_merged.m3u ./iptv_merged.m3u || true
          [ -f ../ip.m3u ] && mv ../ip.m3u ./iptv.m3u || true
          [ -f ../ip_merged.m3u ] && mv ../ip_merged.m3u ./iptv_merged.m3u || true         
          [ -f ../io.m3u ] && mv ../io.m3u ./plutotv.m3u || true
          [ -f ../io_merged.m3u ] && mv ../io_merged.m3u ./plutotv_merged.m3u || true
          [ -f ../rkt.m3u ] && mv ../rkt.m3u ./rakutentv.m3u || true
        fi

        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit."
        else
          git commit -m "Update: $(date +'%Y-%m-%d %H:%M:%S') UTC"
          git push origin main
        fi
